repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: check-toml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: python-no-eval
-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.15.3
    hooks:
    -   id: gitleaks
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: ["--py39-plus"]
-   repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
    -   id: pycln
-   repo: https://github.com/jendrikseipp/vulture
    rev: v2.7
    hooks:
    -   id: vulture
-   repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        additional_dependencies:
            - flake8==5.0.4
            - flake8-bandit==4.1.1
            - flake8-bugbear==23.2.13
            - flake8-builtins==2.1.0
            - flake8-comprehensions==3.10.1
            - flake8-eradicate==1.4.0
            - flake8-functions==0.0.7
            - flake8-gl-codeclimate==0.2.1
            - flake8-logging-format==0.9.0
            - flake8-pyproject==1.2.2
            - flake8-variables-names==0.0.5
            - pep8-naming==0.13.3
            - tryceratops==1.1.0
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
    -   id: mypy
