# This workflow will run multiple jobs in parallel on any commit pushed to
# remote.

name: Test Package and Lint

on: push

jobs:
  # Run unit tests
  tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install portaudio
      run: sudo apt-get install libportaudio2
    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Install python dependencies
      run: poetry install --no-interaction --no-root --with test
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest

  # Run hooks with pre-commit
  pre-commit:
    runs-on: ubuntu-22.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Run pre-commit hooks
      uses: pre-commit/action@v3.0.0
