# This workflow will build Python package and publish it to PyPi

name: Build and Publish Python Package

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          ignore_dev_requirements: true
